#!/bin/bash

install_items=(
    vim
    mc
    fzf
    zsh
    jq
    dmenu
    emacs
    git
    openssh-server
    gnome-tweaks
    curl
    wget
    make
    automake
    gcc
    gcc-c++
    kernel-devel
    cmake
    openssl
    openssl-devel
    zlib
    zlib-devel
    the_silver_searcher
    ripgrep
    xclip
)

symlinks=(
    .zshrc
    .zshenv
    .tmux.conf
    .vimrc
    starttmux
    .gitconfig
    .gitexcludes
    .gitignore
    .irbrc
    .rspec
    custom-functions.el
    todo_file.rb
)

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

echo "Current directory: $DIR"

sudo dnf install -y newt util-linux-user

USER_INPUT=$(whiptail --inputbox "This script will *DELETE* and/or overwrite config files in your HOME directory. Have you read the contents of this setup script and do you want to proceed?\n\n***WARNING***\n\nThis operation cannot be undone - so please make sure you have made a backup of all relevant files.\n\nEnter \"Yes!\" if you want to proceed." 20 60 3>&1 1>&2 2>&3)

exitstatus=$?
echo "User entered " $USER_INPUT

if [ $exitstatus != 0 ]; then
    exit 1
fi

if [ "$USER_INPUT" != "Yes!" ]; then
    exit 1
fi

echo "Installing software..."
sudo dnf install -y "${install_items[@]/#}"

echo "Changing shell to zsh..."
chsh -s $(which zsh)

echo "Oh-my-zsh..."
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

echo "Vundle..."
if [ ! -d "$HOME/.vim/bundle/Vundle.vim" ]; then
    git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
fi

echo "Installing Doom Emacs..."
if [ -d "$HOME/.emacs.d" ]; then
    >&2 echo "There is an existing ~/.emacs.d folder in place. Backup / remove it before continuing."
    exit 1
fi

if [ -d "$HOME/.doom.d" ]; then
    >&2 echo "There is an existing ~/.doom.d folder in place. Backup / remove it before continuing."
    exit 1
fi

git clone --depth 1 https://github.com/hlissner/doom-emacs "$HOME/.emacs.d"
"$HOME/.emacs.d/bin/doom" install

rm $HOME/.doom.d/*.el

ln -s "$DIR/doom/init.el" "$HOME/.doom.d/init.el"
ln -s "$DIR/doom/config.el" "$HOME/.doom.d/config.el"
ln -s "$DIR/doom/packages.el" "$HOME/.doom.d/packages.el"
ln -s "$DIR/doom/custom.el" "$HOME/.doom.d/custom.el"

$HOME/.emacs.d/bin/doom sync

echo "Installing asdf..."
if [ ! -d "$HOME/.asdf" ]; then
    git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf --branch v0.7.8
fi

echo "Creating symlinks..."
for i in "${symlinks[@]}"
do
    if [ ! -f "$HOME/$i" ]; then
        ln -s "$DIR/$i" "$HOME/$i"
    fi
done

echo "Done."
