#!/bin/sh
#
# Slightly modified version of https://gist.github.com/todgru/6224848 - thanks!
#
session="work"

# Set working dir based on first parameter
work_folder="~/work"
current_folder=$work_folder
echo "Current folder: "
echo $current_folder
case $1 in
  ce ) gdk_folder="gdk-ce";;
  ee ) gdk_folder="gdk-ee";;
  dce ) gdk_folder="dev-gdk-ce";;
  dee ) gdk_folder="dev-gdk-ee";;
esac

current_folder="$work_folder/$gdk_folder/gitlab"

# set up tmux
tmux start-server

# create a new tmux session, starting vim from a saved session in the new window
tmux new-session -d -s $session -n vim

# Select pane 1, set dir to work folder, run vim
tmux selectp -t 1
tmux send-keys "cd $current_folder;nvim" C-m

# Split pane 1 vertically
tmux splitw -h -p 20
tmux send-keys "cd $current_folder" C-m

# Select pane 2
tmux selectp -t 2
# Split pane 2 horizontally by 40%
tmux splitw -v -p 50

# select pane 3
tmux selectp -t 3
tmux send-keys "cd $current_folder" C-m

# pane 4 setup
# tmux splitw -h -p 50
# tmux selectp -t 4

# Select pane 1
tmux selectp -t 0

# create a new window called scratch
# tmux new-window -t $session:1 -n scratch

# return to main vim window
# tmux select-window -t $session:0

# Finished setup, attach to the tmux session!
tmux attach-session -t $session
